name: Detect POBR diff

on: [ pull_request ]

concurrency:
  group: detect-pobr-diff-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-pobr-diff:
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/abi-diff.yml@v2.0.5
    with:
      os: ubuntu-24.04
      setup_tools: true
      cc: clang-19
      cxx: clang++-19
      cmake-version: 4.4.0
      conan-version: 2.31.0
      base-branch: ${{ github.base_ref }}
      search-path: >
        include/dice/sparse-map/sparse_growth_policy.hpp
        include/dice/sparse-map/sparse_hash.hpp
        include/dice/sparse-map/sparse_map.hpp
        include/dice/sparse-map/sparse_set.hpp
      abi-version-header: include/dice/sparse-map/version.hpp
      abi-version-const: dice::sparse_map::pobr_version
    secrets:
      CONAN_CICD_ENDPOINT: ${{ secrets.CONAN_CICD_ENDPOINT }}